receivers:
  otlp:
    protocols:
      http:
      grpc:
  
  kafkametrics:
    protocol_version: 2.0.0
    brokers: kafka:9092
    scrapers:
      - brokers
      - topics
      - consumers

exporters:
  logging:

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp, kafkametrics]
      processors: [batch]
      exporters: [logging]
  telemetry:
    logs:
      level: debug
